// ============================================================
// KROK STREET — дані товарів
// Масив об'єктів, що описують товари каталогу.
// ============================================================

const PRODUCTS = [
  {
    id: 1,
    name: "Кросівки Vortex Runner",
    category: "Кросівки",
    brand: "URBN",
    price: 2399,
    oldPrice: null,
    icon: "icon-sneaker",
    art: "imgs/sneakers-first.webp",
    sizes: ["40", "41", "42", "43", "44"],
    inStock: true,
    description: "Легкі бігові кросівки з рельєфною підошвою — тримають зчеплення на будь-якому асфальті."
  },
  {
    id: 2,
    name: "Кросівки Midnight Court",
    category: "Кросівки",
    brand: "NRTH",
    price: 1899,
    oldPrice: 2299,
    icon: "icon-sneaker",
    art: "imgs/sneakers-two.webp",
    sizes: ["40", "41", "42", "43"],
    inStock: true,
    description: "Класична баскетбольна модель у сучасному прочитанні, з підсиленим носком."
  },
  {
    id: 3,
    name: "Кросівки Lime Pulse",
    category: "Кросівки",
    brand: "URBN",
    price: 2199,
    oldPrice: null,
    icon: "icon-sneaker",
    art: "imgs/sneakers-three.webp",
    sizes: ["41", "42", "43", "44"],
    inStock: false,
    description: "Яскрава модель для тих, хто хоче виділятись у натовпі — гнучка підошва, сітчастий верх."
  },
  {
    id: 4,
    name: "Кросівки Steel Frame",
    category: "Кросівки",
    brand: "GRID",
    price: 2650,
    oldPrice: null,
    icon: "icon-sneaker",
    art: "imgs/sneakers-four.webp",
    sizes: ["40", "41", "42", "43", "44"],
    inStock: true,
    description: "Технологічна модель з амортизацією в п’яті — для довгих прогулянок містом."
  },
  {
    id: 5,
    name: "Худі Blockletter",
    category: "Худі",
    brand: "URBN",
    price: 1450,
    oldPrice: null,
    icon: "icon-hoodie",
    art: "imgs/hoodie-first.webp",
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    description: "Щільне худі з великим принтом на спині та кишенею-кенгуру."
  },
  {
    id: 6,
    name: "Худі Cloudwash",
    category: "Худі",
    brand: "GRID",
    price: 1590,
    oldPrice: null,
    icon: "icon-hoodie",
    art: "imgs/hoodie-two.webp",
    sizes: ["XS", "S", "M", "L"],
    inStock: true,
    description: "М’яка бавовна з ефектом «вимитості» — виглядає носеним з першого дня."
  },
  {
    id: 7,
    name: "Худі Night Signal",
    category: "Худі",
    brand: "NRTH",
    price: 1690,
    oldPrice: 1990,
    icon: "icon-hoodie",
    art: "imgs/hoodie-three.webp",
    sizes: ["M", "L", "XL"],
    inStock: true,
    description: "Об’ємний крій, світловідбивний принт спереду — помітно навіть увечері."
  },
  {
    id: 8,
    name: "Худі Concrete",
    category: "Худі",
    brand: "GRID",
    price: 1380,
    oldPrice: null,
    icon: "icon-hoodie",
    art: "imgs/hoodie-four.webp",
    sizes: ["S", "M", "L"],
    inStock: true,
    description: "Легша щільність тканини — для міжсезоння та прохолодних вечорів."
  },
  {
    id: 9,
    name: "Кепка Low Arc",
    category: "Кепки",
    brand: "URBN",
    price: 599,
    oldPrice: null,
    icon: "icon-cap",
    art: "imgs/cap-first.webp",
    sizes: ["S/M", "L/XL"],
    inStock: true,
    description: "Низька посадка, регульований ремінець ззаду, вишитий лого."
  },
  {
    id: 10,
    name: "Кепка Fieldwork",
    category: "Кепки",
    brand: "GRID",
    price: 649,
    oldPrice: 799,
    icon: "icon-cap",
    art: "imgs/cap-two.webp",
    sizes: ["S/M", "L/XL"],
    inStock: true,
    description: "Щільна бавовна кольору хакі-жовтий, підходить під будь-який образ."
  },
  {
    id: 11,
    name: "Кепка Nightshade",
    category: "Кепки",
    brand: "NRTH",
    price: 620,
    oldPrice: null,
    icon: "icon-cap",
    art: "imgs/cap-three.webp",
    sizes: ["S/M"],
    inStock: true,
    description: "Оксамитова текстура і контрастна вишивка спереду."
  },
  {
    id: 12,
    name: "Кепка Sunline",
    category: "Кепки",
    brand: "URBN",
    price: 549,
    oldPrice: null,
    icon: "icon-cap",
    art: "imgs/cap-four.webp",
    sizes: ["S/M", "L/XL"],
    inStock: false,
    description: "Легка модель із сітчастою вставкою ззаду для вентиляції."
  },
  {
    id: 13,
    name: "Футболка Base Tee",
    category: "Футболки",
    brand: "GRID",
    price: 490,
    oldPrice: null,
    icon: "icon-tee",
    art: "imgs/t-shrirt-first.webp",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    description: "Базова футболка щільної в’язки — основа для будь-якого образу."
  },
  {
    id: 14,
    name: "Футболка Blockprint",
    category: "Футболки",
    brand: "URBN",
    price: 590,
    oldPrice: 720,
    icon: "icon-tee",
    art: "imgs/t-shrirt-two.webp",
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    description: "Великий графічний принт на всю грудну зону, оверсайз крій."
  },
  {
    id: 15,
    name: "Футболка Skyline",
    category: "Футболки",
    brand: "NRTH",
    price: 540,
    oldPrice: null,
    icon: "icon-tee",
    art: "imgs/t-shrirt-three.webp",
    sizes: ["S", "M", "L"],
    inStock: true,
    description: "Легка тканина з дрібним принтом силуету міста на рукаві."
  },
  {
    id: 16,
    name: "Футболка Mono Logo",
    category: "Футболки",
    brand: "GRID",
    price: 470,
    oldPrice: null,
    icon: "icon-tee",
    art: "imgs/t-shrirt-four.webp",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    description: "Мінімалістичний лого на грудях, класичний прямий крій."
  }
];
